### PR TITLE
fix: some ui tweaks

### PR DESCRIPTION
**Pull request by stevanlohja**

### CODE REVIEW

**Comment by gilescope** [comment]
1. Can we scrap these self links?
`The <a href="https://releases.midnight.network/">Compact compiler</a>`

It's confusing to link to yourself.

If we could get those links to download the latest compiler that would be amazing.

2. I still don't understand why `compact_0.10.1` is displayed when `compact_0.18.2` is the latest... why is it so hard to download the latest compiler?

**Review by gilescope — APPROVED** [review]

**Comment by its-a-unixsystem** [comment]
The ordering of the versions is still alphabetic and not semver aware.

> compactc_0.10.1
> compactc_0.10.5
> compactc_0.10.6
> compactc_0.18.2 <===== the latest
> compactc_0.8.14 
> compactc_0.9.2

most people will likely download the wrong version (it took me two attempts myself to mark the right one)

**Comment by gilescope** [comment]
Can we apply a non-alphanumeric sort to the `data`, something like this:

```js
        // From https://www.npmjs.com/package/semver-regex (MIT license)
        function semverRegex() {
	        return /(?<=^v?|\sv?)(?:(?:0|[1-9]\d{0,9}?)\.){2}(?:0|[1-9]\d{0,9})(?:-(?:--+)?(?:0|[1-9]\d*|\d*[a-z]+\d*)){0,100}(?=$| |\+|\.)(?:(?<=-\S+)(?:\.(?:--?|[\da-z-]*[a-z-]\d*|0|[1-9]\d*)){1,100}?)?(?!\.)(?:\+(?:[\da-z]\.?-?){1,100}?(?!\w))?(?!\+)/gi;
        }

        function compare(a, b) {
            let a_sem = semverRegex().exec(a);
            let b_sem = semverRegex().exec(b);

            if (a_sem != null && a_sem.len() > 0 && b_sem != null && b_sem.len() > 0) {
                semVal(a.sem) < semVal(b.sem)
            } else {
                // Use alphabet if no semver
                a.name < b.name
            }
        }

        function semVal(val) {
            let parts = val.split('.');
            return int(parts[0]) * 100000 + int(parts[1]) * 1000 + int(parts[2])
        }
```

I'm sketch at JS but something along those lines? If we can do zero knowledge proofs we should be able to sort some files.

**Comment by stevanlohja** [comment]
> 1. Can we scrap these self links?
>    `The <a href="https://releases.midnight.network/">Compact compiler</a>`
> 
> It's confusing to link to yourself.
> 
> If we could get those links to download the latest compiler that would be amazing.
> 
> 2. I still don't understand why `compact_0.10.1` is displayed when `compact_0.18.2` is the latest... why is it so hard to download the latest compiler?

@AEl-Mahdey Has mentinoed he's working on a separate branch for the release ordering issue.

**Comment by stevanlohja** [comment]
I removed 

> 1. Can we scrap these self links?
>    `The <a href="https://releases.midnight.network/">Compact compiler</a>`
> 
> It's confusing to link to yourself.
> 
> If we could get those links to download the latest compiler that would be amazing.
> 
> 2. I still don't understand why `compact_0.10.1` is displayed when `compact_0.18.2` is the latest... why is it so hard to download the latest compiler?

Removed in commit.

**Comment by stevanlohja** [comment]
@AEl-Mahdey also approves. So, merging now.

**Pull request merged**
