### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by AEl-Mahdey**
Small changes to the look and feel of the site.

### CODE REVIEW

**Comment by timjroberts** [comment]
Which Jira ticket was this work for @AEl-Mahdey?

**Review by timjroberts — APPROVED** [review]
DevRel have signed off on the look and feel in the Jira ticket, and these changes look good to me.

**Comment by AEl-Mahdey** [comment]
Thanks, appreciate it!

**Comment by AEl-Mahdey** [comment]
@timjroberts, would you mind merging this. I don't have that permission

**Pull request merged**
